# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ba0b0e5d2542090d93ff0930f1a6de0df07270307df744abb8b22ded38f1a4f36e0721360e4331b597878d2d4c319c48cf3085914aaac6e8c7ac54f1e9cb1b4

test:
  secret_key_base: 02cebcda6b4059cb6e31b5795a0479ad67d4edd7ed26ae6c8454e44e2a58a7ee501976d5086cdea3a38bdc17eea13373ab180a691cc52b2e085d0dd2ad28b08f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
